//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.ResourceManagement.WebServices.Faults
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestFailures", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "Faults")]
    public partial class RequestFailures : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string correlationIdentifierField;
        
        private Microsoft.ResourceManagement.WebServices.WSAddressing.EndpointReferenceType endpointReferenceField;
        
        private Microsoft.ResourceManagement.WebServices.Faults.RequestAdministratorDetails requestAdministratorDetailsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string correlationIdentifier
        {
            get
            {
                return this.correlationIdentifierField;
            }
            set
            {
                this.correlationIdentifierField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Microsoft.ResourceManagement.WebServices.WSAddressing.EndpointReferenceType endpointReference
        {
            get
            {
                return this.endpointReferenceField;
            }
            set
            {
                this.endpointReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Microsoft.ResourceManagement.WebServices.Faults.RequestAdministratorDetails requestAdministratorDetails
        {
            get
            {
                return this.requestAdministratorDetailsField;
            }
            set
            {
                this.requestAdministratorDetailsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestAdministratorDetails", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "Faults")]
    public partial class RequestAdministratorDetails : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string additionalTextDetailsField;
        
        private Microsoft.ResourceManagement.WebServices.Faults.FailedAttributes failedAttributesField;
        
        private string failureMessageField;
        
        private Microsoft.ResourceManagement.WebServices.Exceptions.RequestFailureSource requestFailureSourceField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string additionalTextDetails
        {
            get
            {
                return this.additionalTextDetailsField;
            }
            set
            {
                this.additionalTextDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Microsoft.ResourceManagement.WebServices.Faults.FailedAttributes failedAttributes
        {
            get
            {
                return this.failedAttributesField;
            }
            set
            {
                this.failedAttributesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string failureMessage
        {
            get
            {
                return this.failureMessageField;
            }
            set
            {
                this.failureMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Microsoft.ResourceManagement.WebServices.Exceptions.RequestFailureSource requestFailureSource
        {
            get
            {
                return this.requestFailureSourceField;
            }
            set
            {
                this.requestFailureSourceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FailedAttributes", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "Faults")]
    public partial class FailedAttributes : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string[] attributeTypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string[] attributeType
        {
            get
            {
                return this.attributeTypeField;
            }
            set
            {
                this.attributeTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RepresentationFailures", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "Faults")]
    public partial class RepresentationFailures : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Microsoft.ResourceManagement.WebServices.Faults.AttributeRepresentationFailure[] attributeRepresentationFailuresField;
        
        private string correlationIdentifierField;
        
        private Microsoft.ResourceManagement.WebServices.Faults.MessageRepresentationFailure[] messageRepresentationFailuresField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Microsoft.ResourceManagement.WebServices.Faults.AttributeRepresentationFailure[] attributeRepresentationFailures
        {
            get
            {
                return this.attributeRepresentationFailuresField;
            }
            set
            {
                this.attributeRepresentationFailuresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string correlationIdentifier
        {
            get
            {
                return this.correlationIdentifierField;
            }
            set
            {
                this.correlationIdentifierField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Microsoft.ResourceManagement.WebServices.Faults.MessageRepresentationFailure[] messageRepresentationFailures
        {
            get
            {
                return this.messageRepresentationFailuresField;
            }
            set
            {
                this.messageRepresentationFailuresField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AttributeRepresentationFailure", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "Faults")]
    public partial class AttributeRepresentationFailure : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string additionalTextDetailsField;
        
        private Microsoft.ResourceManagement.WebServices.Exceptions.AttributeFailureCode attributeFailureCodeField;
        
        private string attributeTypeField;
        
        private string attributeValueField;
        
        private string failureMessageField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string additionalTextDetails
        {
            get
            {
                return this.additionalTextDetailsField;
            }
            set
            {
                this.additionalTextDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Microsoft.ResourceManagement.WebServices.Exceptions.AttributeFailureCode attributeFailureCode
        {
            get
            {
                return this.attributeFailureCodeField;
            }
            set
            {
                this.attributeFailureCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string attributeType
        {
            get
            {
                return this.attributeTypeField;
            }
            set
            {
                this.attributeTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string attributeValue
        {
            get
            {
                return this.attributeValueField;
            }
            set
            {
                this.attributeValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string failureMessage
        {
            get
            {
                return this.failureMessageField;
            }
            set
            {
                this.failureMessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageRepresentationFailure", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "Faults")]
    public partial class MessageRepresentationFailure : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string additionalTextDetailsField;
        
        private string failureMessageField;
        
        private Microsoft.ResourceManagement.WebServices.Exceptions.MessageFailureCode messageFailureCodeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string additionalTextDetails
        {
            get
            {
                return this.additionalTextDetailsField;
            }
            set
            {
                this.additionalTextDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string failureMessage
        {
            get
            {
                return this.failureMessageField;
            }
            set
            {
                this.failureMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Microsoft.ResourceManagement.WebServices.Exceptions.MessageFailureCode messageFailureCode
        {
            get
            {
                return this.messageFailureCodeField;
            }
            set
            {
                this.messageFailureCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DispatchRequestFailures", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "Faults")]
    public partial class DispatchRequestFailures : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string correlationIdentifierField;
        
        private Microsoft.ResourceManagement.WebServices.Faults.DispatchRequestAdministratorDetails dispatchRequestAdministratorDetailsField;
        
        private Microsoft.ResourceManagement.WebServices.WSAddressing.EndpointReferenceType endpointReferenceField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string correlationIdentifier
        {
            get
            {
                return this.correlationIdentifierField;
            }
            set
            {
                this.correlationIdentifierField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Microsoft.ResourceManagement.WebServices.Faults.DispatchRequestAdministratorDetails dispatchRequestAdministratorDetails
        {
            get
            {
                return this.dispatchRequestAdministratorDetailsField;
            }
            set
            {
                this.dispatchRequestAdministratorDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Microsoft.ResourceManagement.WebServices.WSAddressing.EndpointReferenceType endpointReference
        {
            get
            {
                return this.endpointReferenceField;
            }
            set
            {
                this.endpointReferenceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DispatchRequestAdministratorDetails", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "Faults")]
    public partial class DispatchRequestAdministratorDetails : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string additionalTextDetailsField;
        
        private Microsoft.ResourceManagement.WebServices.Exceptions.DispatchRequestFailureSource dispatchRequestFailureSourceField;
        
        private string failureMessageField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string additionalTextDetails
        {
            get
            {
                return this.additionalTextDetailsField;
            }
            set
            {
                this.additionalTextDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Microsoft.ResourceManagement.WebServices.Exceptions.DispatchRequestFailureSource dispatchRequestFailureSource
        {
            get
            {
                return this.dispatchRequestFailureSourceField;
            }
            set
            {
                this.dispatchRequestFailureSourceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string failureMessage
        {
            get
            {
                return this.failureMessageField;
            }
            set
            {
                this.failureMessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EndpointFailures", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "Faults")]
    public partial class EndpointFailures : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string correlationIdentifierField;
        
        private Microsoft.ResourceManagement.WebServices.Faults.EndpointAdministratorDetails endpointAdministratorDetailsField;
        
        private Microsoft.ResourceManagement.WebServices.WSAddressing.EndpointReferenceType endpointReferenceField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string correlationIdentifier
        {
            get
            {
                return this.correlationIdentifierField;
            }
            set
            {
                this.correlationIdentifierField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Microsoft.ResourceManagement.WebServices.Faults.EndpointAdministratorDetails endpointAdministratorDetails
        {
            get
            {
                return this.endpointAdministratorDetailsField;
            }
            set
            {
                this.endpointAdministratorDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Microsoft.ResourceManagement.WebServices.WSAddressing.EndpointReferenceType endpointReference
        {
            get
            {
                return this.endpointReferenceField;
            }
            set
            {
                this.endpointReferenceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EndpointAdministratorDetails", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "Faults")]
    public partial class EndpointAdministratorDetails : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string additionalTextDetailsField;
        
        private string failureMessageField;
        
        private Microsoft.ResourceManagement.WebServices.Exceptions.HealthFailureSource healthFailureSourceField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string additionalTextDetails
        {
            get
            {
                return this.additionalTextDetailsField;
            }
            set
            {
                this.additionalTextDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string failureMessage
        {
            get
            {
                return this.failureMessageField;
            }
            set
            {
                this.failureMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Microsoft.ResourceManagement.WebServices.Exceptions.HealthFailureSource healthFailureSource
        {
            get
            {
                return this.healthFailureSourceField;
            }
            set
            {
                this.healthFailureSourceField = value;
            }
        }
    }
}
namespace Microsoft.ResourceManagement.WebServices.WSAddressing
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EndpointReferenceType", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "WSAddressing")]
    public partial class EndpointReferenceType : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Microsoft.ResourceManagement.WebServices.WSAddressing.AttributedURIType addressFieldField;
        
        private Microsoft.ResourceManagement.WebServices.WSAddressing.MetadataType metadataFieldField;
        
        private Microsoft.ResourceManagement.WebServices.WSAddressing.ReferencePropertiesType referencePropertiesFieldField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Microsoft.ResourceManagement.WebServices.WSAddressing.AttributedURIType addressField
        {
            get
            {
                return this.addressFieldField;
            }
            set
            {
                this.addressFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Microsoft.ResourceManagement.WebServices.WSAddressing.MetadataType metadataField
        {
            get
            {
                return this.metadataFieldField;
            }
            set
            {
                this.metadataFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Microsoft.ResourceManagement.WebServices.WSAddressing.ReferencePropertiesType referencePropertiesField
        {
            get
            {
                return this.referencePropertiesFieldField;
            }
            set
            {
                this.referencePropertiesFieldField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AttributedURIType", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "WSAddressing")]
    public partial class AttributedURIType : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string valueFieldField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string valueField
        {
            get
            {
                return this.valueFieldField;
            }
            set
            {
                this.valueFieldField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MetadataType", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "WSAddressing")]
    public partial class MetadataType : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReferencePropertiesType", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "WSAddressing")]
    public partial class ReferencePropertiesType : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Microsoft.ResourceManagement.WebServices.WSResourceManagement.LocaleReferencePropertyType localeReferencePropertyFieldField;
        
        private Microsoft.ResourceManagement.WebServices.WSResourceManagement.ResourceReferencePropertyType resourceReferencePropertyFieldField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Microsoft.ResourceManagement.WebServices.WSResourceManagement.LocaleReferencePropertyType localeReferencePropertyField
        {
            get
            {
                return this.localeReferencePropertyFieldField;
            }
            set
            {
                this.localeReferencePropertyFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Microsoft.ResourceManagement.WebServices.WSResourceManagement.ResourceReferencePropertyType resourceReferencePropertyField
        {
            get
            {
                return this.resourceReferencePropertyFieldField;
            }
            set
            {
                this.resourceReferencePropertyFieldField = value;
            }
        }
    }
}
namespace Microsoft.ResourceManagement.WebServices.WSResourceManagement
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LocaleReferencePropertyType", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "WSResourceManagement")]
    public partial class LocaleReferencePropertyType : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string textFieldField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string textField
        {
            get
            {
                return this.textFieldField;
            }
            set
            {
                this.textFieldField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResourceReferencePropertyType", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "WSResourceManagement")]
    public partial class ResourceReferencePropertyType : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string textFieldField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string textField
        {
            get
            {
                return this.textFieldField;
            }
            set
            {
                this.textFieldField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "WSResourceManagement")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Microsoft.ResourceManagement.WebServices.WSResourceManagement.AuthorizationRequiredFault))]
    public partial class RequestFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Microsoft.ResourceManagement.WebServices.WSAddressing.EndpointReferenceType endpointReferenceField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Microsoft.ResourceManagement.WebServices.WSAddressing.EndpointReferenceType endpointReference
        {
            get
            {
                return this.endpointReferenceField;
            }
            set
            {
                this.endpointReferenceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthorizationRequiredFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "WSResourceManagement")]
    public partial class AuthorizationRequiredFault : Microsoft.ResourceManagement.WebServices.WSResourceManagement.RequestFault
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationRequiredFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "WSResourceManagement")]
    public partial class AuthenticationRequiredFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string securityTokenServiceAddressFieldField;
        
        private System.Nullable<bool> userLockedOutField;
        
        private System.Nullable<bool> userRegisteredField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string securityTokenServiceAddressField
        {
            get
            {
                return this.securityTokenServiceAddressFieldField;
            }
            set
            {
                this.securityTokenServiceAddressFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<bool> userLockedOut
        {
            get
            {
                return this.userLockedOutField;
            }
            set
            {
                this.userLockedOutField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<bool> userRegistered
        {
            get
            {
                return this.userRegisteredField;
            }
            set
            {
                this.userRegisteredField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnonymousInteractionRequiredFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "WSResourceManagement")]
    public partial class AnonymousInteractionRequiredFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Microsoft.ResourceManagement.WebServices.WSResourceManagement.InteractiveWorkflowAddress[] endpointAddressesField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Microsoft.ResourceManagement.WebServices.WSResourceManagement.InteractiveWorkflowAddress[] endpointAddresses
        {
            get
            {
                return this.endpointAddressesField;
            }
            set
            {
                this.endpointAddressesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InteractiveWorkflowAddress", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "WSResourceManagement")]
    public partial class InteractiveWorkflowAddress : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string[] endpointAddressesField;
        
        private System.Guid instanceIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string[] endpointAddresses
        {
            get
            {
                return this.endpointAddressesField;
            }
            set
            {
                this.endpointAddressesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid instanceId
        {
            get
            {
                return this.instanceIdField;
            }
            set
            {
                this.instanceIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CannotProcessFilterFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "WSResourceManagement")]
    public partial class CannotProcessFilterFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvalidExpirationTimeFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "WSResourceManagement")]
    public partial class InvalidExpirationTimeFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnsupportedExpirationTypeFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "WSResourceManagement")]
    public partial class UnsupportedExpirationTypeFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvalidEnumerationContextFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "WSResourceManagement")]
    public partial class InvalidEnumerationContextFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
    }
}
namespace Microsoft.ResourceManagement.WebServices.Exceptions
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestFailureSource", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "Exceptions")]
    public enum RequestFailureSource : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ManagementPolicyRule = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SystemConstraint = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Workflow = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ResourceIsMissing = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Other = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AttributeFailureCode", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "Exceptions")]
    public enum AttributeFailureCode : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ChangeOperationIsNotSupported = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ValueViolatesRegularExpression = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ValueViolatesDataTypeFormat = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RequiredValueIsMissing = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReferencedResourceIsMissing = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AttributeNameViolatesSchema = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ResourceTypeViolatesSchema = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ResourceTypeIsMissing = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SystemAttributeIsReadOnly = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ValueViolatesUniqueness = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Other = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 11,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageFailureCode", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "Exceptions")]
    public enum MessageFailureCode : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DialectIsNotSupported = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RequestMessageViolatesProtocol = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CultureIsNotEnabled = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CultureIsNotSupportedOnOperation = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Other = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DispatchRequestFailureSource", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "Exceptions")]
    public enum DispatchRequestFailureSource : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ServiceIsStopping = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IdentityIsNotFound = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AlternateEndpointNotSupported = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Other = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidResourceIdentifier = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Synchronization = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ActionProcessor = 6,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HealthFailureSource", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "Exceptions")]
    public enum HealthFailureSource : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Other = 0,
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.xmlsoap.org/ws/2004/09/transfer", ConfigurationName="Resource")]
public interface Resource
{
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://schemas.xmlsoap.org/ws/2004/09/transfer/Get", ReplyAction="http://schemas.xmlsoap.org/ws/2004/09/transfer/GetResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.RequestFailures), Action="http://schemas.microsoft.com/2006/11/ResourceManagement/fault", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Name="PermissionDenied", Namespace="http://schemas.microsoft.com/2006/11/ResourceManagement")]
    [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.RepresentationFailures), Action="http://schemas.xmlsoap.org/ws/2004/09/transfer/fault", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Name="InvalidRepresentation")]
    [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.DispatchRequestFailures), Action="http://schemas.microsoft.com/2006/11/IdentityManagement/DirectoryAccess/fault", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Name="UnwillingToPerform", Namespace="http://schemas.microsoft.com/2006/11/IdentityManagement/DirectoryAccess")]
    [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.EndpointFailures), Action="http://www.w3.org/2005/08/addressing/fault", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Name="EndpointUnavailable", Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
    System.ServiceModel.Channels.Message Get(System.ServiceModel.Channels.Message request);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://schemas.xmlsoap.org/ws/2004/09/transfer/Get", ReplyAction="http://schemas.xmlsoap.org/ws/2004/09/transfer/GetResponse")]
    System.Threading.Tasks.Task<System.ServiceModel.Channels.Message> GetAsync(System.ServiceModel.Channels.Message request);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://schemas.xmlsoap.org/ws/2004/09/transfer/Put", ReplyAction="http://schemas.xmlsoap.org/ws/2004/09/transfer/PutResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.WSResourceManagement.AuthorizationRequiredFault), Action="http://schemas.microsoft.com/2006/11/ResourceManagement/fault", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Name="AuthorizationRequiredFault", Namespace="http://schemas.microsoft.com/2006/11/ResourceManagement")]
    [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.RequestFailures), Action="http://schemas.microsoft.com/2006/11/ResourceManagement/fault", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Name="PermissionDenied", Namespace="http://schemas.microsoft.com/2006/11/ResourceManagement")]
    [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.WSResourceManagement.AuthenticationRequiredFault), Action="http://schemas.microsoft.com/2006/11/ResourceManagement/fault", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Name="AuthenticationRequiredFault", Namespace="http://schemas.microsoft.com/2006/11/ResourceManagement")]
    [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.RepresentationFailures), Action="http://schemas.xmlsoap.org/ws/2004/09/transfer/fault", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Name="InvalidRepresentation")]
    [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.WSResourceManagement.AnonymousInteractionRequiredFault), Action="http://schemas.microsoft.com/2006/11/ResourceManagement/fault", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Name="AnonymousInteractionRequiredFault", Namespace="http://schemas.microsoft.com/2006/11/ResourceManagement")]
    [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.DispatchRequestFailures), Action="http://schemas.microsoft.com/2006/11/IdentityManagement/DirectoryAccess/fault", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Name="UnwillingToPerform", Namespace="http://schemas.microsoft.com/2006/11/IdentityManagement/DirectoryAccess")]
    [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.EndpointFailures), Action="http://www.w3.org/2005/08/addressing/fault", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Name="EndpointUnavailable", Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
    System.ServiceModel.Channels.Message Put(System.ServiceModel.Channels.Message request);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://schemas.xmlsoap.org/ws/2004/09/transfer/Put", ReplyAction="http://schemas.xmlsoap.org/ws/2004/09/transfer/PutResponse")]
    System.Threading.Tasks.Task<System.ServiceModel.Channels.Message> PutAsync(System.ServiceModel.Channels.Message request);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://schemas.xmlsoap.org/ws/2004/09/transfer/Delete", ReplyAction="http://schemas.xmlsoap.org/ws/2004/09/transfer/DeleteResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.DispatchRequestFailures), Action="http://schemas.microsoft.com/2006/11/IdentityManagement/DirectoryAccess/fault", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Name="UnwillingToPerform", Namespace="http://schemas.microsoft.com/2006/11/IdentityManagement/DirectoryAccess")]
    [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.RequestFailures), Action="http://schemas.microsoft.com/2006/11/ResourceManagement/fault", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Name="PermissionDenied", Namespace="http://schemas.microsoft.com/2006/11/ResourceManagement")]
    [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.RepresentationFailures), Action="http://schemas.xmlsoap.org/ws/2004/09/transfer/fault", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Name="InvalidRepresentation")]
    [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.EndpointFailures), Action="http://www.w3.org/2005/08/addressing/fault", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Name="EndpointUnavailable", Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
    [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.WSResourceManagement.AuthenticationRequiredFault), Action="http://schemas.microsoft.com/2006/11/ResourceManagement/fault", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Name="AuthenticationRequiredFault", Namespace="http://schemas.microsoft.com/2006/11/ResourceManagement")]
    [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.WSResourceManagement.AuthorizationRequiredFault), Action="http://schemas.microsoft.com/2006/11/ResourceManagement/fault", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Name="AuthorizationRequiredFault", Namespace="http://schemas.microsoft.com/2006/11/ResourceManagement")]
    System.ServiceModel.Channels.Message Delete(System.ServiceModel.Channels.Message request);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://schemas.xmlsoap.org/ws/2004/09/transfer/Delete", ReplyAction="http://schemas.xmlsoap.org/ws/2004/09/transfer/DeleteResponse")]
    System.Threading.Tasks.Task<System.ServiceModel.Channels.Message> DeleteAsync(System.ServiceModel.Channels.Message request);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ResourceChannel : Resource, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ResourceClient : System.ServiceModel.ClientBase<Resource>, Resource
{
    
    public ResourceClient()
    {
    }
    
    public ResourceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ResourceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ResourceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ResourceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.ServiceModel.Channels.Message Get(System.ServiceModel.Channels.Message request)
    {
        return base.Channel.Get(request);
    }
    
    public System.Threading.Tasks.Task<System.ServiceModel.Channels.Message> GetAsync(System.ServiceModel.Channels.Message request)
    {
        return base.Channel.GetAsync(request);
    }
    
    public System.ServiceModel.Channels.Message Put(System.ServiceModel.Channels.Message request)
    {
        return base.Channel.Put(request);
    }
    
    public System.Threading.Tasks.Task<System.ServiceModel.Channels.Message> PutAsync(System.ServiceModel.Channels.Message request)
    {
        return base.Channel.PutAsync(request);
    }
    
    public System.ServiceModel.Channels.Message Delete(System.ServiceModel.Channels.Message request)
    {
        return base.Channel.Delete(request);
    }
    
    public System.Threading.Tasks.Task<System.ServiceModel.Channels.Message> DeleteAsync(System.ServiceModel.Channels.Message request)
    {
        return base.Channel.DeleteAsync(request);
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.xmlsoap.org/ws/2004/09/transfer", ConfigurationName="ResourceFactory")]
public interface ResourceFactory
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/ws/2004/09/transfer/Create", ReplyAction="http://schemas.xmlsoap.org/ws/2004/09/transfer/CreateResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.EndpointFailures), Action="http://www.w3.org/2005/08/addressing/fault", Name="EndpointUnavailable", Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
    [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.RepresentationFailures), Action="http://schemas.xmlsoap.org/ws/2004/09/transfer/fault", Name="InvalidRepresentation")]
    [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.DispatchRequestFailures), Action="http://schemas.microsoft.com/2006/11/IdentityManagement/DirectoryAccess/fault", Name="UnwillingToPerform", Namespace="http://schemas.microsoft.com/2006/11/IdentityManagement/DirectoryAccess")]
    [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.RequestFailures), Action="http://schemas.microsoft.com/2006/11/ResourceManagement/fault", Name="PermissionDenied", Namespace="http://schemas.microsoft.com/2006/11/ResourceManagement")]
    [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.WSResourceManagement.AuthenticationRequiredFault), Action="http://schemas.microsoft.com/2006/11/ResourceManagement/fault", Name="AuthenticationRequiredFault", Namespace="http://schemas.microsoft.com/2006/11/ResourceManagement")]
    [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.WSResourceManagement.AuthorizationRequiredFault), Action="http://schemas.microsoft.com/2006/11/ResourceManagement/fault", Name="AuthorizationRequiredFault", Namespace="http://schemas.microsoft.com/2006/11/ResourceManagement")]
    [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.WSTransfer.DataRequiredFault), Action="http://schemas.microsoft.com/2006/11/ResourceManagement/fault", Name="DataRequiredFault", Namespace="http://schemas.microsoft.com/2006/11/ResourceManagement")]
    System.ServiceModel.Channels.Message Create(System.ServiceModel.Channels.Message request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/ws/2004/09/transfer/Create", ReplyAction="http://schemas.xmlsoap.org/ws/2004/09/transfer/CreateResponse")]
    System.Threading.Tasks.Task<System.ServiceModel.Channels.Message> CreateAsync(System.ServiceModel.Channels.Message request);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ResourceFactoryChannel : ResourceFactory, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ResourceFactoryClient : System.ServiceModel.ClientBase<ResourceFactory>, ResourceFactory
{
    
    public ResourceFactoryClient()
    {
    }
    
    public ResourceFactoryClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ResourceFactoryClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ResourceFactoryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ResourceFactoryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.ServiceModel.Channels.Message Create(System.ServiceModel.Channels.Message request)
    {
        return base.Channel.Create(request);
    }
    
    public System.Threading.Tasks.Task<System.ServiceModel.Channels.Message> CreateAsync(System.ServiceModel.Channels.Message request)
    {
        return base.Channel.CreateAsync(request);
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.xmlsoap.org/ws/2004/09/enumeration", ConfigurationName="Search", SessionMode=System.ServiceModel.SessionMode.NotAllowed)]
public interface Search
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/ws/2004/09/enumeration/Enumerate", ReplyAction="http://schemas.xmlsoap.org/ws/2004/09/enumeration/EnumerateResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.RequestFailures), Action="http://schemas.microsoft.com/2006/11/ResourceManagement/fault", Name="PermissionDenied", Namespace="http://schemas.microsoft.com/2006/11/ResourceManagement")]
    [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.RepresentationFailures), Action="http://schemas.xmlsoap.org/ws/2004/09/transfer/fault", Name="InvalidRepresentation", Namespace="http://schemas.xmlsoap.org/ws/2004/09/transfer")]
    [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.WSEnumeration.SupportedDialect), Action="http://schemas.xmlsoap.org/ws/2004/09/enumeration/fault", Name="FilterDialectRequestedUnavailable")]
    [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.EndpointFailures), Action="http://www.w3.org/2005/08/addressing/fault", Name="EndpointUnavailable", Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
    [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.WSResourceManagement.CannotProcessFilterFault), Action="http://schemas.xmlsoap.org/ws/2004/09/enumeration/fault", Name="CannotProcessFilter")]
    [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.WSResourceManagement.InvalidExpirationTimeFault), Action="http://schemas.xmlsoap.org/ws/2004/09/enumeration/fault", Name="InvalidExpirationTime")]
    [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.WSResourceManagement.UnsupportedExpirationTypeFault), Action="http://schemas.xmlsoap.org/ws/2004/09/enumeration/fault", Name="UnsupportedExpirationType")]
    [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.DispatchRequestFailures), Action="http://schemas.microsoft.com/2006/11/IdentityManagement/DirectoryAccess/fault", Name="UnwillingToPerform", Namespace="http://schemas.microsoft.com/2006/11/IdentityManagement/DirectoryAccess")]
    System.ServiceModel.Channels.Message Enumerate(System.ServiceModel.Channels.Message request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/ws/2004/09/enumeration/Enumerate", ReplyAction="http://schemas.xmlsoap.org/ws/2004/09/enumeration/EnumerateResponse")]
    System.Threading.Tasks.Task<System.ServiceModel.Channels.Message> EnumerateAsync(System.ServiceModel.Channels.Message request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/ws/2004/09/enumeration/Pull", ReplyAction="http://schemas.xmlsoap.org/ws/2004/09/enumeration/PullResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.EndpointFailures), Action="http://www.w3.org/2005/08/addressing/fault", Name="EndpointUnavailable", Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
    [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.RepresentationFailures), Action="http://schemas.xmlsoap.org/ws/2004/09/transfer/fault", Name="InvalidRepresentation", Namespace="http://schemas.xmlsoap.org/ws/2004/09/transfer")]
    [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.RequestFailures), Action="http://schemas.microsoft.com/2006/11/ResourceManagement/fault", Name="PermissionDenied", Namespace="http://schemas.microsoft.com/2006/11/ResourceManagement")]
    [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.WSResourceManagement.InvalidEnumerationContextFault), Action="http://schemas.xmlsoap.org/ws/2004/09/enumeration/fault", Name="InvalidEnumerationContext")]
    [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.DispatchRequestFailures), Action="http://schemas.microsoft.com/2006/11/IdentityManagement/DirectoryAccess/fault", Name="UnwillingToPerform", Namespace="http://schemas.microsoft.com/2006/11/IdentityManagement/DirectoryAccess")]
    System.ServiceModel.Channels.Message Pull(System.ServiceModel.Channels.Message request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/ws/2004/09/enumeration/Pull", ReplyAction="http://schemas.xmlsoap.org/ws/2004/09/enumeration/PullResponse")]
    System.Threading.Tasks.Task<System.ServiceModel.Channels.Message> PullAsync(System.ServiceModel.Channels.Message request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/ws/2004/09/enumeration/Renew", ReplyAction="http://schemas.xmlsoap.org/ws/2004/09/enumeration/RenewResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.DispatchRequestFailures), Action="http://schemas.microsoft.com/2006/11/IdentityManagement/DirectoryAccess/fault", Name="UnwillingToPerform", Namespace="http://schemas.microsoft.com/2006/11/IdentityManagement/DirectoryAccess")]
    [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.WSResourceManagement.InvalidExpirationTimeFault), Action="http://schemas.xmlsoap.org/ws/2004/09/enumeration/fault", Name="InvalidExpirationTime")]
    [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.WSResourceManagement.UnsupportedExpirationTypeFault), Action="http://schemas.xmlsoap.org/ws/2004/09/enumeration/fault", Name="UnsupportedExpirationType")]
    [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.RequestFailures), Action="http://schemas.microsoft.com/2006/11/ResourceManagement/fault", Name="PermissionDenied", Namespace="http://schemas.microsoft.com/2006/11/ResourceManagement")]
    [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.RepresentationFailures), Action="http://schemas.xmlsoap.org/ws/2004/09/transfer/fault", Name="InvalidRepresentation", Namespace="http://schemas.xmlsoap.org/ws/2004/09/transfer")]
    [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.EndpointFailures), Action="http://www.w3.org/2005/08/addressing/fault", Name="EndpointUnavailable", Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
    [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.WSResourceManagement.InvalidEnumerationContextFault), Action="http://schemas.xmlsoap.org/ws/2004/09/enumeration/fault", Name="InvalidEnumerationContext")]
    System.ServiceModel.Channels.Message Renew(System.ServiceModel.Channels.Message request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/ws/2004/09/enumeration/Renew", ReplyAction="http://schemas.xmlsoap.org/ws/2004/09/enumeration/RenewResponse")]
    System.Threading.Tasks.Task<System.ServiceModel.Channels.Message> RenewAsync(System.ServiceModel.Channels.Message request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/ws/2004/09/enumeration/GetStatus", ReplyAction="http://schemas.xmlsoap.org/ws/2004/09/enumeration/GetStatusResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.RequestFailures), Action="http://schemas.microsoft.com/2006/11/ResourceManagement/fault", Name="PermissionDenied", Namespace="http://schemas.microsoft.com/2006/11/ResourceManagement")]
    [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.WSResourceManagement.InvalidEnumerationContextFault), Action="http://schemas.xmlsoap.org/ws/2004/09/enumeration/fault", Name="InvalidEnumerationContext")]
    [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.EndpointFailures), Action="http://www.w3.org/2005/08/addressing/fault", Name="EndpointUnavailable", Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
    [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.DispatchRequestFailures), Action="http://schemas.microsoft.com/2006/11/IdentityManagement/DirectoryAccess/fault", Name="UnwillingToPerform", Namespace="http://schemas.microsoft.com/2006/11/IdentityManagement/DirectoryAccess")]
    [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.RepresentationFailures), Action="http://schemas.xmlsoap.org/ws/2004/09/transfer/fault", Name="InvalidRepresentation", Namespace="http://schemas.xmlsoap.org/ws/2004/09/transfer")]
    System.ServiceModel.Channels.Message GetStatus(System.ServiceModel.Channels.Message request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/ws/2004/09/enumeration/GetStatus", ReplyAction="http://schemas.xmlsoap.org/ws/2004/09/enumeration/GetStatusResponse")]
    System.Threading.Tasks.Task<System.ServiceModel.Channels.Message> GetStatusAsync(System.ServiceModel.Channels.Message request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/ws/2004/09/enumeration/Release", ReplyAction="http://schemas.xmlsoap.org/ws/2004/09/enumeration/ReleaseResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.RepresentationFailures), Action="http://schemas.xmlsoap.org/ws/2004/09/transfer/fault", Name="InvalidRepresentation", Namespace="http://schemas.xmlsoap.org/ws/2004/09/transfer")]
    [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.DispatchRequestFailures), Action="http://schemas.microsoft.com/2006/11/IdentityManagement/DirectoryAccess/fault", Name="UnwillingToPerform", Namespace="http://schemas.microsoft.com/2006/11/IdentityManagement/DirectoryAccess")]
    [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.EndpointFailures), Action="http://www.w3.org/2005/08/addressing/fault", Name="EndpointUnavailable", Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
    [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.WSResourceManagement.InvalidEnumerationContextFault), Action="http://schemas.xmlsoap.org/ws/2004/09/enumeration/fault", Name="InvalidEnumerationContext")]
    [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.RequestFailures), Action="http://schemas.microsoft.com/2006/11/ResourceManagement/fault", Name="PermissionDenied", Namespace="http://schemas.microsoft.com/2006/11/ResourceManagement")]
    System.ServiceModel.Channels.Message Release(System.ServiceModel.Channels.Message request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/ws/2004/09/enumeration/Release", ReplyAction="http://schemas.xmlsoap.org/ws/2004/09/enumeration/ReleaseResponse")]
    System.Threading.Tasks.Task<System.ServiceModel.Channels.Message> ReleaseAsync(System.ServiceModel.Channels.Message request);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface SearchChannel : Search, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class SearchClient : System.ServiceModel.ClientBase<Search>, Search
{
    
    public SearchClient()
    {
    }
    
    public SearchClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public SearchClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public SearchClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public SearchClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.ServiceModel.Channels.Message Enumerate(System.ServiceModel.Channels.Message request)
    {
        return base.Channel.Enumerate(request);
    }
    
    public System.Threading.Tasks.Task<System.ServiceModel.Channels.Message> EnumerateAsync(System.ServiceModel.Channels.Message request)
    {
        return base.Channel.EnumerateAsync(request);
    }
    
    public System.ServiceModel.Channels.Message Pull(System.ServiceModel.Channels.Message request)
    {
        return base.Channel.Pull(request);
    }
    
    public System.Threading.Tasks.Task<System.ServiceModel.Channels.Message> PullAsync(System.ServiceModel.Channels.Message request)
    {
        return base.Channel.PullAsync(request);
    }
    
    public System.ServiceModel.Channels.Message Renew(System.ServiceModel.Channels.Message request)
    {
        return base.Channel.Renew(request);
    }
    
    public System.Threading.Tasks.Task<System.ServiceModel.Channels.Message> RenewAsync(System.ServiceModel.Channels.Message request)
    {
        return base.Channel.RenewAsync(request);
    }
    
    public System.ServiceModel.Channels.Message GetStatus(System.ServiceModel.Channels.Message request)
    {
        return base.Channel.GetStatus(request);
    }
    
    public System.Threading.Tasks.Task<System.ServiceModel.Channels.Message> GetStatusAsync(System.ServiceModel.Channels.Message request)
    {
        return base.Channel.GetStatusAsync(request);
    }
    
    public System.ServiceModel.Channels.Message Release(System.ServiceModel.Channels.Message request)
    {
        return base.Channel.Release(request);
    }
    
    public System.Threading.Tasks.Task<System.ServiceModel.Channels.Message> ReleaseAsync(System.ServiceModel.Channels.Message request)
    {
        return base.Channel.ReleaseAsync(request);
    }
}
namespace Microsoft.ResourceManagement.WebServices.WSTransfer
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataRequiredFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "WSTransfer")]
    public partial class DataRequiredFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
    }
}
namespace Microsoft.ResourceManagement.WebServices.WSEnumeration
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SupportedDialect", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "WSEnumeration")]
    public partial class SupportedDialect : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string textFieldField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string textField
        {
            get
            {
                return this.textFieldField;
            }
            set
            {
                this.textFieldField = value;
            }
        }
    }
}
